### ISSUE TITLE
Use inside of bottomsheet modal

### ISSUE THREAD

**Issue by dayaki** [FerRiv3ra/rn-custom-alert-prompt#1]
Lovely package and UI but I can't seems to get the alert to show up inside of a bottom sheet,  I am guessing the bottomsheet modal is somehow blocking it. Any way around this?

**Comment by FerRiv3ra** [comment]
Thank you, which package are you using for the bottomsheet modal? I imagine that if it is causing some conflict.

**Comment by dayaki** [comment]
I am using this package https://github.com/nysamnang/react-native-raw-bottom-sheet

**Comment by FerRiv3ra** [comment]
I was doing tests and it is indeed a conflict between packages, so I am closing this issue.
